# This workflow will install Python dependencies, check type annotations and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyControl checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install tools and libraries
      run: |
        sudo add-apt-repository -y ppa:velko/dev-tools
        sudo apt-get install -y socat iverilog customasm
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pytest pyserial
    - name: Install localpath helper
      working-directory: ./pycontrol/localpath
      run: |
        python setup.py install
    - name: Generate control ROMs
      working-directory: ./pycontrol/tools
      run: |
        python microcode.py
    - name: Hardware emulator - Verilog testbenches
      working-directory: ./emulator/tests
      run: |
        make test
    - name: Build and start hardware emulator
      working-directory: ./emulator/vm
      run: |
        make
        socat PTY,link=pty0,raw,echo=0 PTY,link=pty1,raw,echo=0 &
        sleep 0.5
        make run &
    - name: Check typing with MyPy
      working-directory: ./pycontrol
      env:
        MYPYPATH: stubs
      run: |
        python -m mypy --strict libcpu tests tools
    - name: Run tests
      working-directory: ./pycontrol
      run: |
        ln -s ../emulator/vm/pty0
        python -m pytest
    - name: Run demo programs
      working-directory: ./demo
      run: |
        ln -s ../emulator/vm/pty0
        customasm hello.asm
        python ../pycontrol/tools/exec_bin.py hello.bin | grep -q "Hello, World!"
        customasm prime_sieve.asm
        python ../pycontrol/tools/exec_bin.py prime_sieve.bin | diff -u primes.txt -
