# This workflow will install Python dependencies, check type annotations and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyControl checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tools and libraries
      run: |
        sudo apt-get install -y socat iverilog
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pytest pyserial
    - name: Install localpath helper
      working-directory: ./pycontrol/localpath
      run: |
        python setup.py install
    - name: Hardware emulator - Verilog testbenches
      working-directory: ./emulator/tests
      run: |
        make test
    - name: Build hardware emulator
      working-directory: ./emulator/vm
      run: |
        make
    - name: Check typing with MyPy
      working-directory: ./pycontrol
      env:
        MYPYPATH: stubs
      run: |
        python -m mypy --strict libcpu tests tools
    - name: Run tests
      working-directory: ./pycontrol
      run: |
        socat PTY,link=pty0,raw,echo=0 PTY,link=../emulator/vm/pty1,raw,echo=0 &
        sleep 0.5
        make -C ../emulator/vm/ run &
        sleep 0.5
        python -m pytest
